#! /bin/sh

sxhkd &
nm-applet &
picom &
fcitx5 &

feh --recursive --randomize --bg-fill ~/Pictures/backgrounds
~/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII 

bspc config border_width         1
bspc config top_padding         58
bspc config window_gap          30
bspc config focused_border_color "#ff0000"

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a vlc state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Sxiv state=floating
bspc rule -a Thunar state=floating
bspc rule -a "VirtualBox Manager" state=floating manage=off
bspc rule -a "VirtualBox Machine" state=floating manage=off
bspc rule -a "baidunetdisk" state=floating
bspc rule -a "netease-cloud-music" state=floating


